generate-image:
	nix build .#topology.x86_64-linux.config.output && sudo cp ./result/* . && sudo chown tyler:users ./*

rebuild:
	git add . && sudo nixos-rebuild switch --flake .#${HOSTNAME}

clean:
	nix-collect-garbage -d && sudo nix-collect-garbage -d && sudo /run/current-system/bin/switch-to-configuration boot
